### ISSUE TITLE
Errors when opening specific performers pages

### ISSUE THREAD

**Issue by Llamrei80** [Valkyr-JS/ValkyrSceneCards#13]
Getting this error when trying to open the perfomer page of Riley Star. So far it only happens on her page, but haven't checked all pages.

`TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at r.default (http://192.168.42.10:9999/plugin/ValkyrSceneCards/javascript:2:3138)
    at r.default (http://192.168.42.10:9999/plugin/ValkyrSceneCards/javascript:2:11050)
    at div
    at div
    at http://192.168.42.10:9999/assets/index-1ea47420.js:44:18273
    at h32 (http://192.168.42.10:9999/assets/index-1ea47420.js:44:406273)
    at http://192.168.42.10:9999/assets/SceneCard-a6aad6f8.js:1:8310
    at div
    at Object.apply (http://192.168.42.10:9999/assets/index-1ea47420.js:44:414205)
    at div
    at div
    at div
    at r (http://192.168.42.10:9999/assets/FrontPage-acfbd1e7.js:1:19255)
    at div
    at div
    at r (http://192.168.42.10:9999/assets/FrontPage-acfbd1e7.js:1:22364)
    at r (http://192.168.42.10:9999/assets/FrontPage-acfbd1e7.js:1:36531)
    at div
    at $ (http://192.168.42.10:9999/assets/FrontPage-acfbd1e7.js:1:39832)
    at qt (http://192.168.42.10:9999/assets/FrontPage-acfbd1e7.js:1:42198)
    at Ee (http://192.168.42.10:9999/assets/FrontPage-acfbd1e7.js:1:43843)
    at jt (http://192.168.42.10:9999/assets/FrontPage-acfbd1e7.js:1:44410)
    at Ut (http://192.168.42.10:9999/assets/FrontPage-acfbd1e7.js:1:45235)
    at div
    at div
    at vr (http://192.168.42.10:9999/assets/FrontPage-acfbd1e7.js:1:45500)
    at t (http://192.168.42.10:9999/assets/index-1ea47420.js:40:9217)
    at t (http://192.168.42.10:9999/assets/index-1ea47420.js:40:11169)
    at Suspense
    at tI (http://192.168.42.10:9999/assets/index-1ea47420.js:44:513735)
    at div
    at a02 (http://192.168.42.10:9999/assets/index-1ea47420.js:54:51421)
    at Ic2 (http://192.168.42.10:9999/assets/index-1ea47420.js:49:3901)
    at T32 (http://192.168.42.10:9999/assets/index-1ea47420.js:44:417715)
    at Suspense
    at L32 (http://192.168.42.10:9999/assets/index-1ea47420.js:44:415831)
    at m32 (http://192.168.42.10:9999/assets/index-1ea47420.js:44:406891)
    at t (http://192.168.42.10:9999/assets/index-1ea47420.js:40:75570)
    at tI (http://192.168.42.10:9999/assets/index-1ea47420.js:44:513735)
    at hg2 (http://192.168.42.10:9999/assets/index-1ea47420.js:64:191504)
    at BG (http://192.168.42.10:9999/assets/index-1ea47420.js:19:183819)
    at t (http://192.168.42.10:9999/assets/index-1ea47420.js:40:5733)
    at t (http://192.168.42.10:9999/assets/index-1ea47420.js:40:12243)`

**Comment by Valkyr-JS** [comment]
Could you send your config settings for the plugin?

**Comment by Llamrei80** [comment]
![Bildschirmfoto_20240714_201751](https://github.com/user-attachments/assets/f1791fb8-a984-41d5-9980-3b85b6369e80)
![Bildschirmfoto_20240714_201818](https://github.com/user-attachments/assets/9203576e-dcaa-45c0-b5ae-f43d84ccdcbe)

**Comment by Llamrei80** [comment]
I found the problem.

One scene had 2 identical files with different names. As soon as i deleted the duplicate file the error disappeared.

**Comment by Valkyr-JS** [comment]
That's really useful thanks, I've added a duplicate and can replicate the error. Will get this fixed.

**Comment by Valkyr-JS** [comment]
Issue caused by `const primaryFile = scene.files.sort((a, b) => b.height - a.height)[0];` in KeyData.tsx. `sort` is unavailable on read-only arrays. Creating a new array fixes this.
